# Generated by Django 5.2.8 on 2025-12-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_agencelivraison'),
    ]

    operations = [
        migrations.AddField(
            model_name='agriculteurprofile',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='agriculteurs/'),
        ),
    ]
