# Generated by Django 5.2.8 on 2025-12-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_agriculteurprofile_photo_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='acheteurprofile',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='acheteurs/'),
        ),
        migrations.AlterField(
            model_name='acheteurprofile',
            name='nom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='acheteurprofile',
            name='prenom',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
