# Generated by Django 6.0 on 2025-12-09 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_acheteurprofile_photo_profil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='agriculteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to=settings.AUTH_USER_MODEL),
        ),
    ]
